---
- hosts: webservers
  tasks:
  - name: install nginx
    package: name=nginx
    become: yes
    notify: save details

  - name: start nginx
    service: name=nginx state=started enabled=yes
    become: yes

  - name: allow http and https
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
    loop:
      - http
      - https
    #when: ansible_distribution=="Fedora"
    become: yes
    notify: restart firewall

  handlers:
  - name: restart firewalld
    service:
      name: firewalld
      state: restarted
    become: yes
    listen: restart firewall

  - name: get details about nginx
    shell: /usr/sbin/nginx -V 2>&1 | grep 'nginx version' | sed 's/.*:\ //'
    register: nginx_version
    listen: save details

  - name: create fact folder for ansible
    file: path=/etc/ansible/facts.d state=directory
    become: yes
    listen: save details

  - name: store nginx details
    copy:
      content: |
        {
          "version": "{{ nginx_version.stdout }}"
        }
      dest: /etc/ansible/facts.d/nginx.fact
    become: yes
    listen: save details
