---
# tasks file for nginx-backend

- name: set start page on RHEL-bases distros
  import_tasks: set-startpage-rhel.yml
  when: ansible_os_family=="RedHat"

- name: set start page on SUSE-bases distros
  import_tasks: set-startpage-suse.yml
  when: ansible_os_family=="Suse"
