---

  - name: setup nginx
    include_tasks: install-nginx.yml

  - name: start nginx
    include_tasks: start-nginx.yml

  - name: configure firewall
    include_tasks: configure-firewall.yml


# tasks file for nginx-base

#- name: install nginx
#  package: name=nginx
#  become: yes
#  notify: save details

#- name: start nginx
#  service: name=nginx state=started enabled=yes
#  become: yes

#- package_facts:
#- name: get details about nginx
#  shell: /usr/sbin/nginx -V 2>&1 | grep 'nginx version' | sed 's/.*:\ //'
#  register: nginx_version
#  listen: save details

#- name: create fact folder for ansible
#  file: path=/etc/ansible/facts.d state=directory
#  become: yes
#  listen: save details

#- name: store nginx details
#  copy:
#    content: |
#      {
#        "version": "{{ ansible_facts.packages.nginx[0].version }}"
#      }
#    dest: /etc/ansible/facts.d/nginx.fact
#  become: yes
#  listen: save details

#- name: allow http and https
#  firewalld:
#    service: "{{ item }}"
#    permanent: yes
#    state: enabled
#    loop:
#      - http
#      - https
    #when: ansible_distribution=="Fedora"
#    become: yes
#    notify: restart firewall
